/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nz.ac.aut.prog2.minesweeper.ui;

import nz.ac.aut.prog2.minesweeper.model.GameLevel;
import nz.ac.aut.prog2.minesweeper.model.MineWorld;

/**
 *
 * @author User
 */
public class MineSweeperUI extends javax.swing.JPanel {
private MineWorld world;
    /**
     * Creates new form MIneSweeperUI
     */
    public MineSweeperUI(MineWorld world) {
        this.world = world;
        initComponents();
        
        world.startGame(GameLevel.BEGINNER);
        update();
    }

    private void update(){
        
        txtWorld.setText(world.getStringRepresentation());
    }

        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtWorld = new javax.swing.JTextArea();

        setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        txtWorld.setColumns(20);
        txtWorld.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txtWorld.setRows(5);
        jScrollPane1.setViewportView(txtWorld);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtWorld;
    // End of variables declaration//GEN-END:variables
}
